# appveyor.yml
build: off

clone_folder: c:\gopath\src\github.com\abdullahselek\go-here

environment:
  GOPATH: c:\gopath

stack:
  - go 1.10
  - go 1.11
  - go 1.12
  - go 1.13
  - go 1.14

before_test:
  - go get -u golang.org/x/lint/golint
  - go get -v -t ./here

test_script:
  - LINT_PATH="$(go list -f {{.Target}} golang.org/x/lint/golint)"
  - $LINT_PATH ./here
  - go test -v ./here
