on: [push, pull_request]
name: Go HERE CI
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.11.x, 1.12.x, 1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Lint
      run: |
        go get -u golang.org/x/lint/golint
    - name: Install go-here
      run: |
        go get -v -t ./here
    - name: Linting
      run: |
        golint ./here
    - name: Tests
      run: |
        go test ./here
